name: qr_application
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  qr_flutter: 4.0.0
  fluttertoast: 8.2.1
  path_provider: 2.0.14
  gallery_saver: 2.3.2
  qr_code_scanner: 1.0.1
  scan: 1.6.0
  image_picker: 0.8.7+4
  animated_text_kit: 4.2.2
  qr_mobile_vision: 4.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

